---
title: "Business Intelligence Project"
author: "<Champions>"
date: "<08/10/2023>"
output:
  github_document: 
    toc: yes
    toc_depth: 4
    fig_width: 6
    fig_height: 4
    df_print: default
editor_options:
  chunk_output_type: console
---

# Student Details

+----------------------------------------------+-----------------------+
| **Student ID Number**                        | 134111                |
|                                              |                       |
|                                              | 133996                |
|                                              |                       |
|                                              | 126761                |
|                                              |                       |
|                                              | 135859                |
|                                              |                       |
|                                              | 127707                |
+----------------------------------------------+-----------------------+
| **Student Name**                             | Juma Immaculate Haayo |
|                                              |                       |
|                                              | Trevor Ngugi          |
|                                              |                       |
|                                              | Virginia Wanjiru      |
|                                              |                       |
|                                              | Pauline Wang'ombe     |
|                                              |                       |
|                                              | Clarice Gitonga       |
+----------------------------------------------+-----------------------+
| **BBIT 4.2 Group**                           | B                     |
+----------------------------------------------+-----------------------+
| **BI Project Group Name/ID (if applicable)** | Champions             |
+----------------------------------------------+-----------------------+

# Setup Chunk

**Note:** the following KnitR options have been set as the global defaults: <BR> `knitr::opts_chunk$set(echo = TRUE, warning = FALSE, eval = TRUE, collapse = FALSE, tidy = TRUE)`.

More KnitR options are documented here <https://bookdown.org/yihui/rmarkdown-cookbook/chunk-options.html> and here <https://yihui.org/knitr/options/>.

```{r setup, include=FALSE}
library(formatR)
knitr::opts_chunk$set(
  warning = FALSE,
  collapse = FALSE
)
```

# Understanding the Dataset (Exploratory Data Analysis (EDA))

## Loading the Dataset

student_performance_dataset \<-

readr::read_csv(

"data/student_performance_dataset.csv", \# nolint

col_types =

readr::cols(

class_group =

readr::col_factor(levels = c("A", "B", "C")),

gender = readr::col_factor(levels = c("1", "0")),

YOB = readr::col_date(format = "%Y"),

regret_choosing_bi =

readr::col_factor(levels = c("1", "0")),

drop_bi_now =

readr::col_factor(levels = c("1", "0")),

motivator =

readr::col_factor(levels = c("1", "0")),

read_content_before_lecture =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

anticipate_test_questions =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

answer_rhetorical_questions =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

find_terms_I_do_not_know =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

copy_new_terms_in_reading_notebook =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

take_quizzes_and_use_results =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

reorganise_course_outline =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

write_down_important_points =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

space_out_revision =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

studying_in_study_group =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

schedule_appointments =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

goal_oriented =

readr::col_factor(levels =

c("1", "0")),

spaced_repetition =

readr::col_factor(levels =

c("1", "2", "3", "4")),

testing_and_active_recall =

readr::col_factor(levels =

c("1", "2", "3", "4")),

interleaving =

readr::col_factor(levels =

c("1", "2", "3", "4")),

categorizing =

readr::col_factor(levels =

c("1", "2", "3", "4")),

retrospective_timetable =

readr::col_factor(levels =

c("1", "2", "3", "4")),

cornell_notes =

readr::col_factor(levels =

c("1", "2", "3", "4")),

sq3r = readr::col_factor(levels =

c("1", "2", "3", "4")),

commute = readr::col_factor(levels =

c("1", "2",

"3", "4")),

study_time = readr::col_factor(levels =

c("1", "2",

"3", "4")),

repeats_since_Y1 = readr::col_integer(),

paid_tuition = readr::col_factor(levels =

c("0", "1")),

free_tuition = readr::col_factor(levels =

c("0", "1")),

extra_curricular = readr::col_factor(levels =

c("0", "1")),

sports_extra_curricular =

readr::col_factor(levels = c("0", "1")),

exercise_per_week = readr::col_factor(levels =

c("0", "1",

"2",

"3")),

meditate = readr::col_factor(levels =

c("0", "1",

"2", "3")),

pray = readr::col_factor(levels =

c("0", "1",

"2", "3")),

internet = readr::col_factor(levels =

c("0", "1")),

laptop = readr::col_factor(levels = c("0", "1")),

family_relationships =

readr::col_factor(levels =

c("1", "2", "3", "4", "5")),

friendships = readr::col_factor(levels =

c("1", "2", "3",

"4", "5")),

romantic_relationships =

readr::col_factor(levels =

c("0", "1", "2", "3", "4")),

spiritual_wellnes =

readr::col_factor(levels = c("1", "2", "3",

"4", "5")),

financial_wellness =

readr::col_factor(levels = c("1", "2", "3",

"4", "5")),

health = readr::col_factor(levels = c("1", "2",

"3", "4",

"5")),

day_out = readr::col_factor(levels = c("0", "1",

"2", "3")),

night_out = readr::col_factor(levels = c("0",

"1", "2",

"3")),

alcohol_or_narcotics =

readr::col_factor(levels = c("0", "1", "2", "3")),

mentor = readr::col_factor(levels = c("0", "1")),

mentor_meetings = readr::col_factor(levels =

c("0", "1",

"2", "3")),

\`Attendance Waiver Granted: 1 = Yes, 0 = No\` =

readr::col_factor(levels = c("0", "1")),

GRADE = readr::col_factor(levels =

c("A", "B", "C", "D",

"E"))),

locale = readr::locale())

### Source:

The dataset that was used can be downloaded here: *\<<https://drive.google.com/drive/folders/1-BGEhfOwquXF6KKXwcvrx7WuZXuqmW9q?usp=sharing>\>*

### Reference:

*\<Cite the dataset here using APA\>\
Refer to the APA 7th edition manual for rules on how to cite datasets: <https://apastyle.apa.org/style-grammar-guidelines/references/examples/data-set-references>*

## Loading the Dataset

```{student_performance_dataset <-}

  readr::read_csv(

    "data/student_performance_dataset.csv", # nolint

    col_types =

      readr::cols(

        class_group =

          readr::col_factor(levels = c("A", "B", "C")),

        gender = readr::col_factor(levels = c("1", "0")),

        YOB = readr::col_date(format = "%Y"),

        regret_choosing_bi =

          readr::col_factor(levels = c("1", "0")),

        drop_bi_now =

          readr::col_factor(levels = c("1", "0")),

        motivator =

          readr::col_factor(levels = c("1", "0")),

        read_content_before_lecture =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        anticipate_test_questions =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        answer_rhetorical_questions =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        find_terms_I_do_not_know =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        copy_new_terms_in_reading_notebook =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        take_quizzes_and_use_results =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        reorganise_course_outline =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        write_down_important_points =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        space_out_revision =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        studying_in_study_group =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        schedule_appointments =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        goal_oriented =

          readr::col_factor(levels =

                              c("1", "0")),

        spaced_repetition =

          readr::col_factor(levels =

                              c("1", "2", "3", "4")),

        testing_and_active_recall =

          readr::col_factor(levels =

                              c("1", "2", "3", "4")),

        interleaving =

          readr::col_factor(levels =

                              c("1", "2", "3", "4")),

        categorizing =

          readr::col_factor(levels =

                              c("1", "2", "3", "4")),

        retrospective_timetable =

          readr::col_factor(levels =

                              c("1", "2", "3", "4")),

        cornell_notes =

          readr::col_factor(levels =

                              c("1", "2", "3", "4")),

        sq3r = readr::col_factor(levels =

                                   c("1", "2", "3", "4")),

        commute = readr::col_factor(levels =

                                      c("1", "2",

                                        "3", "4")),

        study_time = readr::col_factor(levels =

                                         c("1", "2",

                                           "3", "4")),

        repeats_since_Y1 = readr::col_integer(),

        paid_tuition = readr::col_factor(levels =

                                           c("0", "1")),

        free_tuition = readr::col_factor(levels =

                                           c("0", "1")),

        extra_curricular = readr::col_factor(levels =

                                               c("0", "1")),

        sports_extra_curricular =

          readr::col_factor(levels = c("0", "1")),

        exercise_per_week = readr::col_factor(levels =

                                                c("0", "1",

                                                  "2",

                                                  "3")),

        meditate = readr::col_factor(levels =

                                       c("0", "1",

                                         "2", "3")),

        pray = readr::col_factor(levels =

                                   c("0", "1",

                                     "2", "3")),

        internet = readr::col_factor(levels =

                                       c("0", "1")),

        laptop = readr::col_factor(levels = c("0", "1")),

        family_relationships =

          readr::col_factor(levels =

                              c("1", "2", "3", "4", "5")),

        friendships = readr::col_factor(levels =

                                          c("1", "2", "3",

                                            "4", "5")),

        romantic_relationships =

          readr::col_factor(levels =

                              c("0", "1", "2", "3", "4")),

        spiritual_wellnes =

          readr::col_factor(levels = c("1", "2", "3",

                                       "4", "5")),

        financial_wellness =

          readr::col_factor(levels = c("1", "2", "3",

                                       "4", "5")),

        health = readr::col_factor(levels = c("1", "2",

                                              "3", "4",

                                              "5")),

        day_out = readr::col_factor(levels = c("0", "1",

                                               "2", "3")),

        night_out = readr::col_factor(levels = c("0",

                                                 "1", "2",

                                                 "3")),

        alcohol_or_narcotics =

          readr::col_factor(levels = c("0", "1", "2", "3")),

        mentor = readr::col_factor(levels = c("0", "1")),

        mentor_meetings = readr::col_factor(levels =

                                              c("0", "1",

                                                "2", "3")),

        `Attendance Waiver Granted: 1 = Yes, 0 = No` =

          readr::col_factor(levels = c("0", "1")),

        GRADE = readr::col_factor(levels =

                                    c("A", "B", "C", "D",

                                      "E"))),

    locale = readr::locale())

```

## Step 2: Create a subset of the variables/features

We created a subset of the variables to be included in the new dataset.We proceeded to rename the variables to read off white spaces in the variable names.
